---
title: A Bayesian Look On The Selection Of Disputes For Litigation

# to produce blinded version set to 1
blinded: 0

authors: 
- name: Fernando Correa
  thanks: The authors gratefully acknowledge the support of the Brazilian Jurimetrics Association for the support of this research.
  affiliation: Department of Statistics, University of São Paulo
  
- name: Julio Trecenti
  affiliation: Department of Statistics, University of São Paulo
  
- name: Milene Farhat
  affiliation: Department of Statistics, University of São Paulo

keywords:
- jurimetrics, selection, litigation

abstract: |
  [@priest1984selection] is one of the most influencial legal publications of all time. The authors states that the distribution of lawsuits is not the same as the distribution of disputes. Under efficiency and simmetry assumptions, plaintiffs and defendants rationally choose when to prosecute, ensuring that only highly unpredictable disputes becomes lawsuits. Because of its empirical importance, several authors worked through the original example with many interests. Some authors worked on a mathematical formalization of the arguments [@lee2016priest; @waldfogel1995selection; @shapiro1995most; @hylton2011formalization] and others expanded theoretical assumptions [@gelbach2016reduced; @bernardo2000theory; @shavell1996any; @friedman2006litigation]. This paper explores these discussions in a Bayesian flavor. We defined a natural way to consider other sources of variation to the selection process, made the assumptions explicit and provided empirical validation for our suggestions.

bibliography: bibliography.bib
output: rticles::asa_article
---

# Introduction

[@priest1984selection] is one of the most influential legal publications. Recently, its importance has grown as the field of jurimetrics [@loevinger1963jurimetrics], the empirical analysis of the law increases in popularity. \par
  The authors states that the distribution of lawsuit's characteristics is not the same as the distribution of dispute's characteristics. Under efficiency assumptions, plaintiffs and defendants rationally choose when to prosecute, ensuring that only disputes become lawsuits when they disagree in their predictions about the case. \par
  Because of this selection bias, one should be careful when analyzing courts and judges decisions. As an example, one of the most remarkable statements is that the plaintiff's win rate converge to 50\% as the predictions of the parties become more precise. That said, if the hypothesis is true, we should not talk about the facts that generated the lawsuits using lawsuit data, because otherwise we could end up with the same conclusion on various subjects. \par
  Imprecisions on the original paper motivated several authors to work through the model. Some authors worked on a mathematical formalization of the arguments [@lee2016priest; @waldfogel1995selection; @shapiro1995most; @hylton2011formalization] and others expanded theoretical assumptions [@gelbach2016reduced; @bernardo2000theory; @shavell1996any; @friedman2006litigation]. It may be surprising that such and old paper is still being mathematically formalized and not only expanded. This is due the empirical validity of the results and the seminal discussions on the symmetry of information [@waldfogel1998reconciling]. \par
  This paper explores these discussions in a Bayesian flavor. We expand earlier works [@lee2016priest] giving the problem a full decision-theoretic approach [@degroot2005optimal]. Doing this, we defined a natural way to consider other sources of variation to the selection process, made some earlier assumptions explicit and provided empirical validation for our suggestions.

\section{A Bayesian look on the classical model}

[@priest1984selection] doesn't formally prove it's claims because it relies on empirical simulations. The original notation is not perfectly suitable for the discussions proposed in this paper. To proceed with the Bayesian modelling of the problem, we'll follow a mix of the notations and definitions proposed by [@gelbach2016reduced] and [@lee2016priest]. Our main objective is to construct a notation that is both precise and loyal to the original setting.

\subsection{The decision process}

Every dispute has a case merit $Y$ that represents the case reality. It has some distribution $g(y)$ that resumes the variation of disputes. If $Y$ is larger than some fixed legal standard $y^*$, then the plaintiff wins. If it's smaller than $y^*$, then the defendant wins. In our setting, $y^*$ is assumed to be known.

The selection of disputes for litigation comes from the decision making of the parties, based on noisy measures of $Y$. The original model assumes that the plaintiff $p$ and the defendant $d$ accesses the case merit with the conditionally independent random variables $Y_p|Y \sim N(Y, \sigma)$ and $Y_d|Y \sim N(Y, \sigma)$, respectively.

The parties _know_ that their noisy measurements are normally distributed and proceed computing their expected probabilities of winning an eventual litigation. On the classical setting, the posterior probabilities of the plaintiff's win is given by:

$$ q_p = \Phi\left(\frac{Y_p - y^*}{\sigma}\right) \text{ and }q_d = \Phi\left(\frac{Y_d-y^*}{\sigma}\right).$$

Before the decision process the parties define the expected cost of settlement and the expected cost of litigation. The usual setting consider the following inputs:

- $c_p$, the fixed cost of litigation for the plaintiff (possibly null).
- $c_d$, the fixed cost of litigation for the defendant (also possibly null).
- $s_p$, the fixed cost of a settlement for the plaintiff.
- $s_d$, the fixed cost of a settlement for the defendant.
- $J$, the expected cost of the defendant if the plaintiff wins
- $J_p = \alpha J$, $\alpha \in [0,1]$, the benefits for the defendant if the plaintiff loses.

The expected cost/losses are defined as:

1. Plaintiff's expected win if a litigation has occurred: $L_p = q_pJ\alpha-c_p$
2. Defendant's expected cost if a litigation has occurred: $L_d = q_dJ+c_d$
<!-- - $s_p$, the cost of pre-processual settlement for the plaintiff. -->
<!-- - $s_d$, the cost of pre-processual settlement for the defendant. -->

<!-- Priest and Klein paper adds some parameters to the usual setting: $J$, $\alpha$, $Y$, $Y_d$ and $Y_p$. $Y$ is a random quantity that indicates the true quality of the case and $Y_d$ and $Y_p$ are noisy approximations of $Y$ that are accessible for the parties. $Y$ and $y^*$ are numerical representations of lawsuit's variability and court decision criterion: if $Y > y^*$, some threshold number defined by the court, the plaintiff wins the case. -->

After an implicit decision process, the literature accepts that $q_pJ\alpha-c_p+s_p > q_dJ+c_d-s_d$ is a sufficient (and necessary) condition for litigation. The intuition behind this statement comes from a more detailed the description of those quantities:

1. $q_dJ+c_d-s_d$ is the largest amount the defendant is willing to pay in a settlement. 
2. $q_pJ\alpha-c_p+s_p$ is the lowest amount the plaintiff is willing to receive in a settlement. 

Doing some algebra we have that the litigation condition is equivalent to

$$ q_p - \frac{q_d}{\alpha}>  +  \frac{c_p + c_d - s_d-s_p}{\alpha J}, $$

that will therefore be called Landes-Posner-Gould (LPG) condition [@landes1971economic; @posner1973economic; @gould1973economics]. 

\subsection{Results}

The LPG framework is important because it implies important empirical statements [@lee2016priest]:

1. Disputes selected for litigation (as opposed to settlement) will not constitute a random sample nor a representative sample of all disputes.

2. As the parties error diminishes and the litigation rates declines, the proportion of plaintiff victories approaches 50%.

3. Regardless of legal standard, the plaintiff trial win rate exhibit "a strong bias toward fifty percent" as compared to the plaintiff trial win rate that would be observed if every case went to trial.

4. If the defendant would lose more from an adverse judgement than the plaintiff would gain, then the plaintiff will win less than fifty percent of the litigated cases. Conversely, if the plaintiff has more to gain, then the plaintiff will win more than fifty percent of the cases.

5. The plaintiff trial win rate will be unrelated to the shape of the distribution of disputes. This hypothesis is about the plaintiff win rate in the limit as the parties become increasingly accurate in predicting trial outcomes. 

6. Because selection effects are strong, no inferences can be made about the law or legal decision makers from the plaintiff win rate. Rather, "the proportion of observed plaintiff victories will tend to remains constant".

\section{A Bayesian Look}

The decision making that leads to the LPG condition might be formulated as follows:

- \textbf{Assumption 1} The parties assume conditionally independent normally distributed measurements $Y_p| \sim N(Y, \sigma)$ and $Y_d|\sim N(Y, \sigma)$. 
- \textbf{Assumption 2} The priors on $Y$ are independent and flat.
- \textbf{Assumption 3} Both the parties knows $y^*$, with no uncertainty.
- \textbf{Assumption 4} The decision process that results in settlements or litigation has two steps. First, the plaintiff proposes a settlement value for the defendant. Second, the defendant accept or rejects the offer, based on his beliefs and $Y_d$. The acceptance of rejection of the defendant is what defines the litigation.
- \textbf{Assumption 5} The costs of settlement, litigation and payoffs are fixed and known by both parties, with no uncertainty.
- \textbf{Assumption 6} The plaintiff decides for a settlement value offer $v$ that is the Bayes decision using the loss $L_p(v, y) = (v-\left(I(y < y^*)J - c_p + s_p\right))^2$.  
- \textbf{Assumption 7} The defendant accepts ($a = 1$) or rejects ($a = 0$) the value offer $v$ with the Bayes decision considering the loss $L_d(a, v, y) = (1-a)(I(y < y^*)J - c_d) + a(v+s_d)$.

Some of those assumptions, like assumption 2 and 1, are very restrictive from a Bayesian point of view. In this paper we look forward to relax some requirements of the original setting and obtaining generalized versions of the original results. \par

Assumption 3, for example, maybe replaced  with another one that defines a noisy measurement of $y^*$. This produces a generalized version of the second result defined above.
